sudo : required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t tom1130/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true tom1130/docker-react-app npm run test -- --coverage

deploy:
  provider : elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-862844162274"
  bucket_path : "docker-react-app"
  on:
    branch: master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key : $AWS_SECRET_ACCESS_KEY

after_success:
  - echo "Test Success"